# docker-compose.yml
version: '3'
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"